### ISSUE TITLE
Missing second "o" in "Honolulu"

### ISSUE THREAD

**Issue by dchan3** [daveyshindig/daveyshindig.github.io#1]
Br,

Yu mitted a letter in yur HTML. Just CTRL+F fr "KTUH FM" in yur HTML, and yu'll see it. S bnxius.

Peace & lve,
dchan3 (aka DJ Kdekrakkerz)

P.S. See hw it feels t be reading this?

**Comment by daveynight** [comment]
OK Derek, thanks and all for pointing it out but there's really no need to rub my nose in my (very small) mistake, which was literally a single typo
